# Generated by Django 5.2.7 on 2025-10-11 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, help_text='Users that this user has blocked', related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='muted_users',
            field=models.ManyToManyField(blank=True, help_text='Users that this user has muted', related_name='muted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
