# Generated by Django 5.2.7 on 2025-10-09 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_likes_count_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='posts.post')),
            ],
            options={
                'indexes': [models.Index(fields=['hashtag', 'created_at'], name='posts_posth_hashtag_84643a_idx')],
                'unique_together': {('post', 'hashtag')},
            },
        ),
    ]
