# Generated by Django 5.2.7 on 2025-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posthashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_settings',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('following', 'People you follow'), ('mentioned', 'People you mentioned')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
