# Generated by Django 5.2.7 on 2025-10-09 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_is_highlighted_post_is_pinned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('post_view', 'Post View'), ('post_impression', 'Post Impression'), ('engagement_click', 'Engagement Click'), ('video_play', 'Video Play'), ('profile_visit', 'Profile Visit'), ('navigation', 'Navigation Event')], max_length=20)),
                ('event_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(null=True)),
                ('referrer', models.URLField(null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='posts_analy_event_t_c6967d_idx'), models.Index(fields=['post', 'event_type', 'timestamp'], name='posts_analy_post_id_d2244b_idx'), models.Index(fields=['user', 'event_type', 'timestamp'], name='posts_analy_user_id_d1e69d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('view_type', models.CharField(choices=[('feed', 'Feed View'), ('detail', 'Detail Page View'), ('impression', 'Feed Impression')], default='feed', max_length=20)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_duration', models.IntegerField(null=True)),
                ('referrer', models.URLField(null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_views', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'viewed_at'], name='posts_postv_post_id_0d76ce_idx'), models.Index(fields=['user', 'post', 'viewed_at'], name='posts_postv_user_id_2eb5e4_idx'), models.Index(fields=['ip_address', 'post', 'viewed_at'], name='posts_postv_ip_addr_a6a0ce_idx'), models.Index(fields=['session_key', 'post', 'viewed_at'], name='posts_postv_session_2d1051_idx')],
            },
        ),
    ]
