# Generated by Django 5.2.7 on 2025-10-09 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_analyticsevent_postview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('delete_post', 'Delete Post'), ('pin_post', 'Pin Post'), ('unpin_post', 'Unpin Post'), ('highlight_post', 'Highlight Post'), ('unhighlight_post', 'Unhighlight Post'), ('change_reply_settings', 'Change Reply Settings'), ('add_to_list', 'Add to List'), ('remove_from_list', 'Remove from List'), ('request_community_note', 'Request Community Note'), ('view_engagements', 'View Engagements'), ('view_analytics', 'View Analytics'), ('embed_post', 'Embed Post')], max_length=30)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=10)),
                ('details', models.JSONField(default=dict, help_text='Additional context for the action')),
                ('target_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action_type', 'timestamp'], name='posts_posta_user_id_824b3f_idx'), models.Index(fields=['target_post', 'timestamp'], name='posts_posta_target__f2d142_idx')],
            },
        ),
    ]
