# Generated by Django 5.2.7 on 2025-10-11 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_athlete_league_team_league_teams_athlete_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(help_text='Original uploaded file', upload_to='media/original/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type', max_length=100)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of media', max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in pixels', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds (for videos)', null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail size URL (150x150)')),
                ('preview_url', models.URLField(blank=True, help_text='Preview size URL (800x600)')),
                ('full_url', models.URLField(blank=True, help_text='Full size URL')),
                ('video_thumbnail_url', models.URLField(blank=True, help_text='Video thumbnail frame')),
                ('hls_playlist_url', models.URLField(blank=True, help_text='HLS playlist URL for streaming')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['media_type', 'processing_status'], name='posts_media_media_t_dda305_idx'), models.Index(fields=['created_at'], name='posts_media_created_0df5a2_idx')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.ForeignKey(blank=True, help_text='Processed media file with multiple sizes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.mediafile'),
        ),
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('thumbnail', 'Thumbnail'), ('preview', 'Preview'), ('full', 'Full Size'), ('hls_segment', 'HLS Segment'), ('hls_playlist', 'HLS Playlist')], help_text='Type of variant', max_length=20)),
                ('file_url', models.URLField(help_text='URL to the processed file')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in pixels', null=True)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('format', models.CharField(blank=True, help_text='File format (jpg, mp4, m3u8, etc.)', max_length=10)),
                ('segment_index', models.PositiveIntegerField(blank=True, help_text='HLS segment index', null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, help_text='Video bitrate in kbps', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_file', models.ForeignKey(help_text='Parent media file', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='posts.mediafile')),
            ],
            options={
                'ordering': ['variant_type', 'segment_index'],
                'indexes': [models.Index(fields=['media_file', 'variant_type'], name='posts_media_media_f_7829f8_idx'), models.Index(fields=['variant_type', 'created_at'], name='posts_media_variant_91d8ca_idx')],
                'unique_together': {('media_file', 'variant_type', 'segment_index')},
            },
        ),
    ]
