# Generated by Django 5.2.7 on 2025-10-11 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_mediafile_post_media_file_mediavariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Stream title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Stream description')),
                ('stream_key', models.CharField(help_text='Unique stream key for RTMP', max_length=100, unique=True)),
                ('playback_url', models.URLField(blank=True, help_text='HLS playback URL')),
                ('stream_url', models.URLField(blank=True, help_text='RTMP stream URL for broadcasting')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('starting', 'Starting'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('peak_viewers', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Stream thumbnail/preview image')),
                ('tags', models.JSONField(default=list, help_text='Stream tags/categories')),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users allowed to view private streams', related_name='allowed_streams', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveStreamView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('view_type', models.CharField(choices=[('viewer', 'Regular Viewer'), ('host', 'Stream Host')], default='viewer', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('watch_duration', models.IntegerField(null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='posts.livestream')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['status', 'scheduled_start'], name='posts_lives_status_ed1996_idx'),
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['host', 'status'], name='posts_lives_host_id_d32eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['created_at'], name='posts_lives_created_dbd087_idx'),
        ),
        migrations.AddIndex(
            model_name='livestreamview',
            index=models.Index(fields=['stream', 'joined_at'], name='posts_lives_stream__a7471d_idx'),
        ),
        migrations.AddIndex(
            model_name='livestreamview',
            index=models.Index(fields=['user', 'stream'], name='posts_lives_user_id_266de4_idx'),
        ),
    ]
