# Generated by Django 5.2.7 on 2025-10-14 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_livestream_livestreamview_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="postactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("delete_post", "Delete Post"),
                    ("pin_post", "Pin Post"),
                    ("unpin_post", "Unpin Post"),
                    ("highlight_post", "Highlight Post"),
                    ("unhighlight_post", "Unhighlight Post"),
                    ("change_reply_settings", "Change Reply Settings"),
                    ("add_to_list", "Add to List"),
                    ("remove_from_list", "Remove from List"),
                    ("request_community_note", "Request Community Note"),
                    ("view_engagements", "View Engagements"),
                    ("view_analytics", "View Analytics"),
                    ("embed_post", "Embed Post"),
                    ("share_post", "Share Post"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PostShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        default="unknown",
                        help_text="Platform where post was shared",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "created_at"],
                        name="posts_posts_post_id_72b2c4_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="posts_posts_user_id_c4f83d_idx",
                    ),
                    models.Index(
                        fields=["platform", "created_at"],
                        name="posts_posts_platfor_102c8a_idx",
                    ),
                ],
                "unique_together": {("post", "user", "platform")},
            },
        ),
    ]
