# Generated by Django 5.2.7 on 2025-10-14 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_post_shares_count_alter_postactionlog_action_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name='repost',
            old_name='post',
            new_name='original_post',
        ),
        migrations.AddField(
            model_name='repost',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment for quote reposts'),
        ),
        migrations.AddField(
            model_name='repost',
            name='repost_post',
            field=models.OneToOneField(blank=True, help_text='The new post created for this repost (for quote posts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_repost', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
