# Generated by Django 5.2.7 on 2025-10-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_alter_repost_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
