# Generated by Django 5.2.7 on 2025-10-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_post_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
