# Generated by Django 5.2.7 on 2025-10-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0017_add_reply_count_to_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
