# Generated by Django 5.2.7 on 2025-10-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0018_add_comments_count_to_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reposts_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
