# Generated by Django 5.2.7 on 2025-10-13 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "sport",
                    models.CharField(
                        help_text="e.g., basketball, football, baseball", max_length=50
                    ),
                ),
                ("description", models.TextField()),
                (
                    "standings",
                    models.JSONField(default=dict, help_text="Standings data as JSON"),
                ),
                (
                    "feed_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for the league's feed",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField()),
                (
                    "roster",
                    models.JSONField(
                        default=list, help_text="Team roster as JSON array"
                    ),
                ),
                (
                    "schedule",
                    models.JSONField(
                        default=list, help_text="Team schedule as JSON array"
                    ),
                ),
                (
                    "feed_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for the team's feed",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="sports.league",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("position", models.CharField(max_length=50)),
                ("nationality", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "feed_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for the athlete's feed",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athletes",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
