# Generated by Django 5.2.7 on 2025-10-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country where league is played", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="Cached logo URL from API-Football", null=True
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="popularity_score",
            field=models.IntegerField(
                default=0, help_text="Popularity score for explore page ranking"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="follower_count",
            field=models.IntegerField(
                default=0, help_text="Number of users following this team"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="Cached logo URL from API-Football", null=True
            ),
        ),
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="API-Football fixture ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("home_team_name", models.CharField(max_length=100)),
                ("away_team_name", models.CharField(max_length=100)),
                ("home_team_id", models.IntegerField()),
                ("away_team_id", models.IntegerField()),
                ("league_name", models.CharField(max_length=100)),
                ("league_id", models.IntegerField()),
                ("scheduled_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        help_text="Match status (e.g., NS, FT, HT)", max_length=20
                    ),
                ),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scheduled_time"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_time"], name="sports_fixt_schedul_450255_idx"
                    ),
                    models.Index(
                        fields=["status"], name="sports_fixt_status_e5f046_idx"
                    ),
                    models.Index(
                        fields=["league_id"], name="sports_fixt_league__138f99_idx"
                    ),
                ],
            },
        ),
    ]
